### ISSUE TITLE
locking memory page

### ISSUE THREAD

**Issue by joeyh** [vincenthz/hs-securemem#1]
For this to be used for eg, storing crypto keys, it would be great if the memory page could be locked to prevent it being paged out to disk. gnupg does this, and with recent versions of linux, unpriviliged programs are allowed to do it.

I don't know if the implementation using the haskell heap allows this to be done.

**Comment by joeyh-purism** [comment]
http://cse.iitk.ac.in/users/ppk/posts/2016-08-02-Handling-Secure-Memory-in-Raaz.html

**Comment by kirelagin** [comment]
`libsodium` has pretty cool functions for allocating secure memory: https://libsodium.gitbook.io/doc/memory_management#guarded-heap-allocations. I was going to make a package that would expose this functionality to Haskell, but then found `securemem`. So, I’m wondering, would you be interested in a PR that would make `SecureMem` much slower and much more secure at the cost of depending on Sodium?
