### ISSUE TITLE
SecureMem equality is incorrect

### ISSUE THREAD

**Issue by dnaq** [vincenthz/hs-securemem#9]
```
>>> let a = secureMemFromByteString "\0abc"
>>> let b = secureMemFromByteString "\0\0\0\0"
>>> a == b
True
```

This is with securemem-0.1.9.

**Comment by vincenthz** [comment]
ah bad. the constant equality has not been updated just like the equality function. it's fixed in memory 0.9 (securemem has nothing to do with this anymore)
